from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd


def ensure_qlib_official_graphs(
    rec: Any,
    *,
    dataset: Any | None = None,
    segment: str = "test",
    prefix: str = "qlib",
    strict: bool = False,
    force: bool = False,
) -> Tuple[Dict[str, List[str]], Dict[str, str]]:
    """
    Load Qlib official graphs from recorder; if missing, generate them.

    Returns
    -------
    (graphs, errors)
      - graphs: Dict[graph_name, List[filename]]
      - errors: Dict[graph_name, error_message]
    """
    graphs: Dict[str, List[str]] = {}
    errors: Dict[str, str] = {}

    if not force:
        try:
            graphs = rec.load_object("qlib_official_graphs") or {}
        except Exception:
            graphs = {}
        try:
            errors = rec.load_object("qlib_official_graphs_errors") or {}
        except Exception:
            errors = {}
        if graphs:
            return graphs, errors

    graphs = export_qlib_official_graphs(
        rec,
        dataset=dataset,
        segment=segment,
        prefix=prefix,
        strict=strict,
    )

    # `export_qlib_official_graphs` always best-effort saves both objects, even if empty.
    try:
        errors = rec.load_object("qlib_official_graphs_errors") or {}
    except Exception:
        errors = {}
    return graphs, errors


def load_label_df_from_recorder(rec: Any) -> Optional[pd.DataFrame]:
    """
    Strictly load the raw label generated by Qlib official SignalRecord (DK_R) from recorder artifact `label.pkl`.
    """
    try:
        label_df = rec.load_object("label.pkl")
    except Exception:
        return None

    if isinstance(label_df, pd.Series):
        label_df = label_df.to_frame("label")

    if not isinstance(label_df, pd.DataFrame) or label_df.shape[0] == 0 or label_df.shape[1] < 1:
        return None

    df = label_df.iloc[:, [0]].copy()
    df.columns = ["label"]
    return ensure_qlib_instrument_datetime_index(df)


def ensure_qlib_instrument_datetime_index(df: pd.DataFrame) -> pd.DataFrame:
    """
    Qlib contrib.report expects a 2-level MultiIndex ordered as (instrument, datetime) for some graphs
    (e.g. cumulative_return_graph / rank_label_graph slice on the 2nd level as datetime).
    Recorder artifacts are often saved as (datetime, instrument). Normalize here.
    """
    if not isinstance(df, pd.DataFrame):
        return df
    if not isinstance(df.index, pd.MultiIndex) or df.index.nlevels != 2:
        return df

    idx = df.index
    names = list(idx.names)

    # Fast path: already named, just reorder if necessary
    if set(names) == {"instrument", "datetime"}:
        if names != ["instrument", "datetime"]:
            df = df.reorder_levels(["instrument", "datetime"])
        df = df.sort_index()
        df.index.names = ["instrument", "datetime"]
        return df

    def _is_dt(level) -> bool:
        try:
            return pd.api.types.is_datetime64_any_dtype(level)
        except Exception:
            pass
        try:
            v0 = level[0]
        except Exception:
            return False
        return isinstance(v0, pd.Timestamp)

    lv0 = idx.get_level_values(0)
    lv1 = idx.get_level_values(1)
    lv0_is_dt = _is_dt(lv0)
    lv1_is_dt = _is_dt(lv1)

    # Common case: (datetime, instrument) -> reorder to (instrument, datetime)
    if lv0_is_dt and not lv1_is_dt:
        df = df.reorder_levels([1, 0]).sort_index()
        df.index.names = ["instrument", "datetime"]
        return df

    # Fallback: keep order but set canonical names if it looks right
    if lv1_is_dt and not lv0_is_dt:
        df = df.sort_index()
        df.index.names = ["instrument", "datetime"]
        return df

    return df


def export_qlib_official_graphs(
    rec: Any,
    *,
    dataset: Any | None = None,
    segment: str = "test",
    prefix: str = "qlib",
    strict: bool = True,
) -> Dict[str, List[str]]:
    """
    Generate and save Qlib official analysis graphs into recorder local_dir.

    Notes
    -----
    - This function only uses artifacts stored in `rec` (e.g. pred.pkl/label.pkl/portfolio_analysis/*).
      Therefore it must be called after SignalRecord + PortAnaRecord have been generated.
    - It always attempts to save `qlib_official_graphs` and `qlib_official_graphs_errors` (possibly empty),
      so that downstream code can safely call `rec.load_object(...)` without KeyError.
    """
    try:
        import qlib.contrib.report as qcr
        import qlib.contrib.report.analysis_position  # noqa: F401
        import qlib.contrib.report.analysis_model  # noqa: F401
    except Exception as e:
        if strict:
            raise RuntimeError(f"Failed to import qlib.contrib.report: {e}") from e
        # Still persist empty outputs for stable downstream load.
        try:
            rec.save_objects(qlib_official_graphs={})
            rec.save_objects(qlib_official_graphs_errors={"__import__": str(e)})
        except Exception:
            pass
        return {}

    import inspect
    import warnings

    local_dir: Path = Path(rec.get_local_dir())
    try:
        local_dir.mkdir(parents=True, exist_ok=True)
    except Exception:
        pass

    out: Dict[str, List[str]] = {}
    errors: Dict[str, str] = {}

    # Inputs from recorder (created by PortAnaRecord / SignalRecord)
    report_normal_df = None
    analysis_df = None
    try:
        report_normal_df = rec.load_object("portfolio_analysis/report_normal_1day.pkl")
    except Exception:
        report_normal_df = None
    try:
        analysis_df = rec.load_object("portfolio_analysis/port_analysis_1day.pkl")
    except Exception:
        analysis_df = None

    pred_df = None
    try:
        pred_df = rec.load_object("pred.pkl")
    except Exception:
        pred_df = None

    label_df = load_label_df_from_recorder(rec)

    # Normalize pred/label formats to match qlib.contrib.report expectations
    if isinstance(pred_df, pd.Series):
        pred_df = pred_df.to_frame("score")
    if isinstance(pred_df, pd.DataFrame) and pred_df.shape[1] >= 1:
        if "score" not in pred_df.columns and pred_df.shape[1] == 1:
            pred_df = pred_df.copy()
            pred_df.columns = ["score"]
        pred_df = ensure_qlib_instrument_datetime_index(pred_df)

    pred_label = None
    if isinstance(label_df, pd.DataFrame) and isinstance(pred_df, pd.DataFrame):
        lbl = label_df[["label"]] if "label" in label_df.columns else label_df.iloc[:, [0]].copy()
        lbl.columns = ["label"]
        prd = pred_df[["score"]] if "score" in pred_df.columns else pred_df.iloc[:, [0]].copy()
        prd.columns = ["score"]
        pred_label = pd.concat([lbl, prd], axis=1, sort=True).reindex(lbl.index)

    positions = None
    try:
        positions = rec.load_object("portfolio_analysis/positions_normal_1day.pkl")
    except Exception:
        positions = None

    available = {
        # 原始 key
        "report_normal_df": report_normal_df,
        "analysis_df": analysis_df,
        "pred_label": pred_label,
        "positions": positions,
        # === 别名映射 (qlib 函数实际参数名) ===
        "report_df": report_normal_df,  # report_graph 需要
        "position": positions,  # cumulative_return_graph, rank_label_graph 需要
        "report_normal": report_normal_df,  # cumulative_return_graph 需要
        "label_data": label_df,  # cumulative_return_graph, rank_label_graph 需要
    }

    def _describe_df(df: Any, name: str) -> str:
        if df is None:
            return f"{name}=None"
        if not isinstance(df, pd.DataFrame):
            return f"{name}={type(df).__name__}"
        msg = f"{name}.shape={df.shape}"
        try:
            msg += f", nan_frac={float(df.isna().mean().mean()):.3f}"
        except Exception:
            pass
        try:
            if isinstance(df.index, pd.MultiIndex) and "datetime" in df.index.names:
                dts = pd.to_datetime(df.index.get_level_values("datetime"))
                if len(dts) > 0:
                    msg += f", dt=[{dts.min().date()}..{dts.max().date()}]"
        except Exception:
            pass
        return msg

    def _describe_positions(pos: Any) -> str:
        if pos is None:
            return "positions=None"
        if not isinstance(pos, dict):
            return f"positions={type(pos).__name__}"
        n_days = len(pos)
        if n_days == 0:
            return "positions=dict(days=0)"

        holding_counts: List[int] = []
        nonempty_days = 0
        for _, v in pos.items():
            try:
                if hasattr(v, "position"):
                    d = dict(v.position)
                elif isinstance(v, dict):
                    d = dict(v)
                else:
                    continue
                d.pop("cash", None)
                d.pop("now_account_value", None)
                cnt = len(d)
                holding_counts.append(cnt)
                if cnt > 0:
                    nonempty_days += 1
            except Exception:
                continue
        try:
            dt_min = min(pos.keys())
            dt_max = max(pos.keys())
        except Exception:
            dt_min, dt_max = None, None

        if holding_counts:
            avg = float(np.mean(holding_counts))
            mn = int(np.min(holding_counts))
            mx = int(np.max(holding_counts))
        else:
            avg, mn, mx = 0.0, 0, 0
        return (
            f"positions=dict(days={n_days}, nonempty_days={nonempty_days}, "
            f"holdings(avg/min/max)={avg:.1f}/{mn}/{mx}, dt=[{dt_min}..{dt_max}])"
        )

    def _date_overlap_hint() -> str:
        try:
            if not isinstance(positions, dict) or not isinstance(label_df, pd.DataFrame):
                return ""
            if label_df.empty or len(positions) == 0:
                return ""
            pos_dates = pd.to_datetime(list(positions.keys())).normalize()
            lbl_dates = pd.to_datetime(label_df.index.get_level_values("datetime")).normalize()
            overlap = len(set(pos_dates) & set(lbl_dates))
            return f"date_overlap(positions,label_df)={overlap}"
        except Exception:
            return ""

    def _auto_call(fn):
        sig = inspect.signature(fn)
        kwargs = {}
        for name, p in sig.parameters.items():
            # 跳过 **kwargs 类型参数
            if p.kind == inspect.Parameter.VAR_KEYWORD:
                continue
            if name == "show_notebook":
                kwargs[name] = False
                continue
            if name in available and available[name] is not None:
                kwargs[name] = available[name]
            elif p.default is inspect._empty and p.kind in (
                inspect.Parameter.POSITIONAL_ONLY,
                inspect.Parameter.POSITIONAL_OR_KEYWORD,
            ):
                raise TypeError(f"Missing required arg: {name}")
        return fn(**kwargs)

    def _resolve_graph_fn(graph_name: str):
        obj = qcr
        for part in graph_name.split("."):
            obj = getattr(obj, part)
        return obj

    graph_names = []
    try:
        graph_names = list(getattr(qcr, "GRAPH_NAME_LIST"))
    except Exception:
        graph_names = []

    if not graph_names:
        graph_names = [
            "analysis_position.report_graph",
            "analysis_position.score_ic_graph",
            "analysis_position.cumulative_return_graph",
            "analysis_position.risk_analysis_graph",
            "analysis_position.rank_label_graph",
            "analysis_model.model_performance_graph",
        ]

    for gname in graph_names:
        fn = _resolve_graph_fn(gname)
        file_prefix = f"{prefix}_{gname.replace('.', '_')}"
        try:
            graph_output = _auto_call(fn)
        except Exception as e:
            msg = f"Failed to run Qlib graph '{gname}': {e}"
            if strict:
                raise RuntimeError(msg) from e
            errors[gname] = msg
            warnings.warn(msg)
            continue

        try:
            figures = coerce_graph_output_to_figures(graph_output)
        except Exception as e:
            msg = f"Failed to collect figures for Qlib graph '{gname}': {e}"
            if strict:
                raise RuntimeError(msg) from e
            errors[gname] = msg
            warnings.warn(msg)
            continue

        if not figures:
            hints = [
                f"Qlib graph '{gname}' returned no figure objects.",
                _describe_positions(positions),
                _describe_df(report_normal_df, "report_normal_df"),
                _describe_df(analysis_df, "analysis_df"),
                _describe_df(label_df, "label_df"),
                _describe_df(pred_df, "pred_df"),
            ]
            ov = _date_overlap_hint()
            if ov:
                hints.append(ov)
            msg = "\n".join([h for h in hints if h])
            if strict:
                raise RuntimeError(msg)
            errors[gname] = msg
            warnings.warn(msg)
            continue

        try:
            fns = save_graph_figures(local_dir=local_dir, prefix=file_prefix, figures=figures)
        except Exception as e:
            msg = f"Failed to save figures for Qlib graph '{gname}': {e}"
            if strict:
                raise RuntimeError(msg) from e
            errors[gname] = msg
            warnings.warn(msg)
            continue

        if not fns:
            msg = (
                f"Qlib graph '{gname}' produced figure objects but none could be saved. "
                f"figure_types={[type(f).__name__ for f in figures][:5]}"
            )
            if strict:
                raise RuntimeError(msg)
            errors[gname] = msg
            warnings.warn(msg)
            continue

        out[gname] = fns

    # Always persist for stable downstream load, even if empty.
    try:
        rec.save_objects(qlib_official_graphs=out)
    except Exception:
        pass
    try:
        rec.save_objects(qlib_official_graphs_errors=errors)
    except Exception:
        pass
    return out


def coerce_graph_output_to_figures(graph_output) -> List[object]:
    """
    Normalize qlib.contrib.report graph outputs into a list of figure-like objects.

    Qlib report graphs may return:
    - plotly / matplotlib figure objects
    - iterables / generators of figures
    - dicts mapping names -> figures
    - graph wrapper objects that expose `.figure` / `.fig`
    """

    def _is_figure_like(x) -> bool:
        return hasattr(x, "write_html") or hasattr(x, "savefig")

    def _unwrap(x):
        if x is None:
            return None
        if _is_figure_like(x):
            return x
        for attr in ("figure", "fig"):
            try:
                v = getattr(x, attr)
            except Exception:
                v = None
            if v is not None and _is_figure_like(v):
                return v
        return None

    def _collect(x) -> List[object]:
        if x is None:
            return []

        fig = _unwrap(x)
        if fig is not None:
            return [fig]

        if isinstance(x, dict):
            out: List[object] = []
            for v in x.values():
                out.extend(_collect(v))
            return out

        if isinstance(x, (list, tuple, set)):
            out: List[object] = []
            for v in x:
                out.extend(_collect(v))
            return out

        # Avoid iterating over strings/bytes (iterates characters)
        if isinstance(x, (str, bytes)):
            return []

        # Generator / iterable of unknown objects
        try:
            it = iter(x)
        except TypeError:
            return []

        out: List[object] = []
        for v in it:
            out.extend(_collect(v))
        return out

    return _collect(graph_output)


def save_graph_figures(
    *,
    local_dir: Path,
    prefix: str,
    figures: List[object],
    dpi: int = 150,
) -> List[str]:
    """
    Save a list of figure objects into local_dir.

    Priority:
    - Plotly Figure: save `.html` (`include_plotlyjs="directory"` for offline viewing).
    - Matplotlib Figure: save `.png`.

    Notes
    -----
    - We intentionally prefer `.html` for plotly to avoid requiring kaleido (png export dependency).
    - `include_plotlyjs="directory"` writes `plotly.min.js` next to the html files (no network needed).
    """
    figs = list(figures) if figures else []
    out: List[str] = []
    for i, fig in enumerate(figs):
        base = prefix if len(figs) == 1 else f"{prefix}_{i+1}"

        # Matplotlib
        if hasattr(fig, "savefig"):
            try:
                fn = f"{base}.png"
                fig.savefig(local_dir / fn, dpi=dpi, bbox_inches="tight")
                out.append(fn)
                continue
            except Exception:
                pass

        # Plotly
        if hasattr(fig, "write_html"):
            try:
                fn = f"{base}.html"
                fig.write_html(str(local_dir / fn), include_plotlyjs="directory", full_html=True)
                out.append(fn)
                continue
            except Exception:
                pass

    return out

